import React, { Fragment } from "react";
import Marquee from "react-fast-marquee";

export default function CommodityStockTicker({ direction = "left" }) {
  const commodities_ticker = [
    {
      ticker: "GOLD",
      company_name: "Barrick Gold Corporation",
      commodity: "Gold",
      market_cap: "44.29B",
      dividend_yield: "1.47%",
      pe_ratio: "13.05",
      eps: "2.32",
      beta: "0.20",
      market_change: 0.75,
    },
    {
      ticker: "SILV",
      company_name: "SilverCrest Metals Inc.",
      commodity: "Silver",
      market_cap: "1.78B",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "0",
      beta: "1.13",
      market_change: -1.2,
    },
    {
      ticker: "CL=F",
      company_name: "Crude Oil WTI",
      commodity: "Crude Oil",
      market_cap: "0",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "0",
      beta: "0",
      market_change: 0.5,
    },
    {
      ticker: "HMY",
      company_name: "Harmony Gold Mining Company Limited",
      commodity: "Gold",
      market_cap: "4.54B",
      dividend_yield: "1.08%",
      pe_ratio: "10.88",
      eps: "0.47",
      beta: "0.14",
      market_change: 0.3,
    },
    {
      ticker: "AG",
      company_name: "First Majestic Silver Corp.",
      commodity: "Silver",
      market_cap: "2.76B",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "0",
      beta: "2.16",
      market_change: -0.8,
    },
    {
      ticker: "XOM",
      company_name: "Exxon Mobil Corporation",
      commodity: "Crude Oil",
      market_cap: "292.71B",
      dividend_yield: "5.55%",
      pe_ratio: "16.27",
      eps: "3.77",
      beta: "1.23",
      market_change: -0.1,
    },
    {
      ticker: "RIO",
      company_name: "Rio Tinto Group",
      commodity: "Iron Ore",
      market_cap: "124.35B",
      dividend_yield: "5.31%",
      pe_ratio: "11.89",
      eps: "11.72",
      beta: "1.08",
      market_change: 1.2,
    },
    {
      ticker: "BHP",
      company_name: "BHP Group",
      commodity: "Iron Ore",
      market_cap: "195.52B",
      dividend_yield: "4.20%",
      pe_ratio: "15.44",
      eps: "5.45",
      beta: "1.07",
      market_change: 0,
    },
    {
      ticker: "GLNCY",
      company_name: "Glencore PLC",
      commodity: "Copper",
      market_cap: "68.27B",
      dividend_yield: "3.87%",
      pe_ratio: "8.19",
      eps: "1.30",
      beta: "1.31",
      market_change: -0.5,
    },
    {
      ticker: "VALE",
      company_name: "Vale S.A.",
      commodity: "Iron Ore",
      market_cap: "123.84B",
      dividend_yield: "6.22%",
      pe_ratio: "7.53",
      eps: "3.48",
      beta: "1.37",
      market_change: -1.1,
    },
    {
      ticker: "NEM",
      company_name: "Newmont Corporation",
      commodity: "Gold",
      market_cap: "56.09B",
      dividend_yield: "2.86%",
      pe_ratio: "13.21",
      eps: "4.15",
      beta: "0.19",
      market_change: 0.8,
    },
    {
      ticker: "CDE",
      company_name: "Coeur Mining, Inc.",
      commodity: "Silver",
      market_cap: "2.07B",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "0",
      beta: "2.33",
      market_change: 0.6,
    },
    {
      ticker: "CVX",
      company_name: "Chevron Corporation",
      commodity: "Crude Oil",
      market_cap: "286.14B",
      dividend_yield: "4.70%",
      pe_ratio: "28.03",
      eps: "5.67",
      beta: "1.25",
      market_change: -0.3,
    },
    {
      ticker: "FCX",
      company_name: "Freeport-McMoRan Inc.",
      commodity: "Copper",
      market_cap: "60.28B",
      dividend_yield: "0.99%",
      pe_ratio: "8.56",
      eps: "4.12",
      beta: "2.49",
      market_change: -0.2,
    },
    {
      ticker: "PBR",
      company_name: "Petroleo Brasileiro S.A. - Petrobras",
      commodity: "Crude Oil",
      market_cap: "97.08B",
      dividend_yield: "3.55%",
      pe_ratio: "15.84",
      eps: "1.02",
      beta: "1.84",
      market_change: 0.7,
    },
    {
      ticker: "WPM",
      company_name: "Wheaton Precious Metals Corp.",
      commodity: "Silver",
      market_cap: "21.12B",
      dividend_yield: "1.19%",
      pe_ratio: "35.07",
      eps: "1.43",
      beta: "0.43",
      market_change: 1.5,
    },
    {
      ticker: "MRO",
      company_name: "Marathon Oil Corporation",
      commodity: "Crude Oil",
      market_cap: "17.32B",
      dividend_yield: "2.11%",
      pe_ratio: "21.63",
      eps: "1.00",
      beta: "2.50",
      market_change: -0.4,
    },
    {
      ticker: "TECK",
      company_name: "Teck Resources Limited",
      commodity: "Copper",
      market_cap: "16.77B",
      dividend_yield: "0.61%",
      pe_ratio: "18.97",
      eps: "1.25",
      beta: "1.81",
      market_change: 0.9,
    },
    {
      ticker: "EQNR",
      company_name: "Equinor ASA",
      commodity: "Crude Oil",
      market_cap: "96.54B",
      dividend_yield: "3.67%",
      pe_ratio: "27.78",
      eps: "1.48",
      beta: "0.91",
      market_change: -0.6,
    },
    {
      ticker: "EXK",
      company_name: "Endeavour Silver Corp.",
      commodity: "Silver",
      market_cap: "292.86M",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "0",
      beta: "1.58",
      market_change: 0.3,
    },
    {
      ticker: "APC",
      company_name: "Anadarko Petroleum Corporation",
      commodity: "Crude Oil",
      market_cap: "0",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "0",
      beta: "0",
      market_change: 0,
    },
    {
      ticker: "NUE",
      company_name: "Nucor Corporation",
      commodity: "Iron Ore",
      market_cap: "35.91B",
      dividend_yield: "1.90%",
      pe_ratio: "11.90",
      eps: "6.53",
      beta: "1.46",
      market_change: 0.2,
    },
    {
      ticker: "LUNMF",
      company_name: "Lundin Mining Corporation",
      commodity: "Copper",
      market_cap: "7.38B",
      dividend_yield: "1.97%",
      pe_ratio: "13.63",
      eps: "0.65",
      beta: "1.66",
      market_change: -0.7,
    },
    {
      ticker: "COPX",
      company_name: "Global X Copper Miners ETF",
      commodity: "Copper",
      market_cap: "0",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "0",
      beta: "0",
      market_change: 0,
    },
    {
      ticker: "CEQP",
      company_name: "Crestwood Equity Partners LP",
      commodity: "Crude Oil",
      market_cap: "2.77B",
      dividend_yield: "9.43%",
      pe_ratio: "11.59",
      eps: "1.28",
      beta: "1.54",
      market_change: -0.9,
    },
    {
      ticker: "HES",
      company_name: "Hess Corporation",
      commodity: "Crude Oil",
      market_cap: "28.16B",
      dividend_yield: "1.38%",
      pe_ratio: "0",
      eps: "-15.62",
      beta: "1.55",
      market_change: 0.4,
    },
    {
      ticker: "SLCA",
      company_name: "U.S. Silica Holdings, Inc.",
      commodity: "Silica",
      market_cap: "308.16M",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "-2.90",
      beta: "1.77",
      market_change: -0.6,
    },
    {
      ticker: "LNG",
      company_name: "Cheniere Energy, Inc.",
      commodity: "Natural Gas",
      market_cap: "27.74B",
      dividend_yield: "0.54%",
      pe_ratio: "50.23",
      eps: "1.30",
      beta: "0.76",
      market_change: 0.2,
    },
    {
      ticker: "WLL",
      company_name: "Whiting Petroleum Corporation",
      commodity: "Crude Oil",
      market_cap: "6.57B",
      dividend_yield: "0%",
      pe_ratio: "0",
      eps: "-0.53",
      beta: "3.05",
      market_change: -0.8,
    },
    {
      ticker: "SAND",
      company_name: "Sandstorm Gold Ltd.",
      commodity: "Gold",
      market_cap: "1.99B",
      dividend_yield: "1.35%",
      pe_ratio: "126.38",
      eps: "0.11",
      beta: "0.11",
      market_change: 1.1,
    },
  ];

  return (
    <Fragment>
      <Marquee gradient="true" direction={direction}>
        <div className="flex space-x-4">
          {commodities_ticker.map((commodity, index) => {
            return (
              <div
                className="p-2 text-sm flex space-x-2 rounded-lg"
                key={index}
              >
                <span className="font-semibold">{commodity.commodity}</span>
                <span className="text-gray-500">{commodity.market_cap}</span>
                <span
                  className={`${
                    commodity.market_change > 0
                      ? "text-green-500"
                      : "text-red-400"
                  }`}
                >
                  {commodity.market_change} %
                </span>
              </div>
            );
          })}
        </div>
      </Marquee>
    </Fragment>
  );
}
